import { model } from "../model";
import { SAFETY_SETTINGS } from "../safety-settings";

export async function generateStory(title: string) {
  const generationConfig = {
    temperature: 0.8,
    topK: 1,
    topP: 1,
    maxOutputTokens: 2048,
  };

  const parts = [
    {
      text: "I want you to act as Reddit user posting an extremely interesting and sometimes over the top thread story. I will give you the title of the story and you will respond with the most insane and over the top story, yet still believable. The story should be written like a Reddit user sharing their story to the internet. Make sure the story is still believable. Generate at least 400 words of story. Do not use fancy words, write the story like someone sharing it to a friend. I want you to only respond with the story and nothing else, do not write explanation. Make sure to write a teenager accessible stories. Do not use explicit words. Don't use the real name for anything (people, websites, street name, etc.).",
    },
    {
      text: "input: Ruin my sister's only birth experience? I'll make sure you NEVER forget her",
    },
    {
      text: "output: When I was 14 and my sister Sarah was 22, she found out she was having a baby with her boyfriend Paul. They planned to get married, but things got tough around the 4th or 5th month. Being pregnant wasn't easy for her. She felt awful most of the time, and it seemed like everything hurt. To top it off, Paul didn't understand what she was going through. He'd even get annoyed when she complained, saying things like, \"Everyone experiences pregnancy differently.\" As the due date approached, things became even more stressful. Sarah really wanted to avoid giving birth on Valentine's Day, but there's no controlling these things. The big day arrived, and while I was too young to be in the delivery room, I remember feeling frustrated that Paul wouldn't go in either. He claimed he couldn't handle the sight of it, which really upset me. He just didn't seem to get what my sister was going through. After a long labor, my nephew finally arrived - right on Valentine's Day. Sadly, there were complications. During surgery, doctors discovered a large, non-cancerous growth in Sarah's uterus. They had to remove it completely, meaning she wouldn't be able to have any more children. It was a lot to take in, especially while still recovering from childbirth. While Sarah was in surgery, Paul took care of the baby. He seemed worried at first, but then my older brother, Zeke, noticed something strange. Paul was filling out the birth certificate, including the baby's name. Zeke found it odd that he wouldn't wait for Sarah to wake up, but Paul claimed he just wanted her to rest. Here's the crazy part: despite knowing how much Sarah disliked the name, Paul wrote down \"Valentino\" on the birth certificate - the same name his family had been pushing for. He even had his parents sign as witnesses, claiming Sarah had already approved it. Of course, that was completely untrue. As soon as Sarah was well enough, she changed the baby's name and ended things with Paul. He vanished for a while, and then, six months later, she saw his wedding photos online! Turns out, he had been cheating on her well before the baby was even born. It was a lot for Sarah to deal with, but she stayed strong. She raised her son on her own, filed for child support, and eventually moved on with her life. It wasn't easy, but she proved she could handle anything life threw her way.",
    },
    {
      text: "input: I GROUNDED my son after he PAINTED his nails, now he hasn't spoken to me for an ENTIRE YEAR",
    },
    {
      text: "output: Man, I love my son, but I'd be lying if I said I wasn't bummed about the whole self-expression journey he's on. Ever since middle school, he's totally embraced this unique style, starting with all black clothes. Now in high school, it's gone, well, let's just say pretty loud. Baggy black everything, tons of accessories, the whole shebang. At one point, he even had streaks of colour in his hair, which, let's just say, wasn't exactly my jam. Look, I'm totally cool with people being themselves, whoever that is. But I guess I always pictured my son growing up a bit more...traditional. You know, the whole \"man's man\" thing. It doesn't help that most of his close friends are girls. They're all super nice and respectful, but it just feels...off, you know? Like he's missing out on the whole \"guy bonding\" experience. I try to be chill about his whole look, even though sometimes he honestly reminds me of those kids from the old 90s movies. But there was this one time, about a year ago, that pushed me over the edge. He came home with his nails painted bright blue, and I just...couldn't. I told him it was a bit much and that maybe he should tone it down a bit. We weren't exactly close, so he looked pretty hurt, but I felt like he needed a reality check. Things got heated. He called me out for being judgmental, and I ended up grounding him for, like, forever (well, a year, which felt like forever at the time). Took away his phone, all that jazz. All he did was stay in his room, talking to his friends and basically ignoring me. One night, I even heard him crying to my wife, but she just reminded him that I'm his dad and he needs to respect me. It hasn't been easy. We haven't spoken in a while, and I miss him, honestly. He graduates next year, and I just hope he understands that I just want what's best for him, even if it doesn't always feel like it.",
    },
    {
      text: "input: What was the BEST relationship advice you have ever received?",
    },
    {
      text: "output: As our awesome older brother, Justin McElroy, says, relationships are  all about teamwork. Both people should always strive to be giving their  best effort, even if it means stepping outside their comfort zone  sometimes. Small gestures like showing something you made or taking the  dog for a walk can make a big difference. I read that these little  things can truly show someone you care, more than just grand gestures.  Big moments build the foundation, but the little daily actions fill in  the gaps and make the relationship strong. This advice came from someone  close to me, not Justin, but my mom. When she and my dad were going  through a rough patch, she was venting to her friend about all the  things she wished her husband would do differently. But her friend asked  a thought-provoking question: \"What are you willing to change about  yourself?\" This made my mom realize that she wasn't perfect either, and  if she wanted things to improve, she needed to be willing to work on  herself and meet him halfway. They've been happily together for over 25  years because of that. Remember, strong feelings don't guarantee a  lasting relationship. There will be disagreements, but always remember  it's you and your partner against the problem, not against each other.  Even if you're married, keep the spark alive! Make time for each other,  and go out of your way to show you care. Open communication is key. Be  honest and open about finances, feelings, and anything else that might  impact your relationship. Treat each other with respect, always. Never  put your partner down, especially in front of others, and always be  there to support them when they need you. Look for someone who genuinely  lights up when they see you, someone whose eyes communicate their love  and excitement. Remember, a healthy relationship is a team effort. Be  honest, supportive, and always strive to grow together. Don't ignore any  warning signs, and be brave enough to walk away if someone isn't  treating you right. You deserve to be with someone who helps you reach  your full potential!",
    },
    {
      text: "input: What's that one hack that everyone should know before WORKING OUT?",
    },
    {
      text: "output: 1. Many protein products might not be as effective as advertised. The listed protein content might not be entirely accurate, making it tricky to know exactly how much you're consuming. This is because companies can manipulate the nitrogen levels, which are often used to estimate protein content, to appear higher than it actually is. This practice, called amino spiking, allows them to use cheaper ingredients and save money while potentially misleading consumers. On the other hand, hemp bars are a good alternative. They typically contain protein and fiber, which can help boost metabolism and keep you feeling full for longer, potentially reducing your dependence on green juices. It's important to clarify that hemp has no psychoactive effects, unlike other products associated with the number 420. Additionally, hemp bars are generally more affordable than green juices. 2. Contrary to popular belief, eggs are a healthy choice. The cholesterol found in eggs doesn't necessarily translate to higher blood cholesterol levels in everyone, making them a safe and natural source of protein for building and maintaining muscle health, which can ultimately support weight management goals. 3. Contrary to what you might have heard, starting your day with coffee, even on an empty stomach, isn't inherently bad for you. Your body adapts to your routines, so if you enjoy a morning cup of coffee, go for it! 4. Those trendy green powders claiming to heal your gut or eliminate bloating are likely overhyped. Their high fiber content might actually lead to digestive discomfort instead of the promised benefits. Instead of relying on these products, focusing on incorporating more vegetables into your diet is a more sustainable and effective approach. 5. Pushing yourself to do the same workout repeatedly can lead to stagnation in your progress, as your body adapts and stops responding as effectively. Taking rest days is crucial for allowing your body to recover and rebuild, leading to better long-term results. 6. Eating past 8 pm doesn't automatically lead to weight gain. What matters most is your overall calorie intake throughout the day. The idea that nighttime eating is detrimental likely stems from the fact that cravings can be stronger in the evening due to lower inhibitions, leading to potential overeating, which can happen at any time of day. 7. Your body doesn't always send clear signals for thirst. Sometimes, what feels like hunger pangs might actually be your body's way of telling you it needs hydration. Staying adequately hydrated can help you feel fuller for longer and make better dietary choices, ultimately aiding your weight management journey. Remember, proper hydration is essential for overall health and well-being, not just weight management.",
    },
    { text: "input: My PARENTS want me to take CARE of my SISTER'S KID." },
    {
      text: "output: My twin sister and I, both 18, are our parents' only children. However, we had very different personalities. My sister was the social butterfly, while I preferred spending time with friends discussing books and shows. My parents, unfortunately, seemed to favor my sister's charisma, leaving me feeling misunderstood and often excluded. Now, in our senior year, my hard work in a special program had earned me acceptances to prestigious colleges with full scholarships. Meanwhile, my sister received acceptance to a local college, but faced an unexpected challenge - she was pregnant, and the father was absent. This news brought the first wave of genuine disappointment I'd ever seen from my parents towards my sister. However, their disapproval quickly faded. They devised a plan to help her raise the baby while still attending college, and without any discussion with me, they included me in this plan. They sat me down and revealed that I would be attending the local college with my sister, but only part-time, as they expected me to help care for the baby. My sister, on the other hand, would attend full-time while taking care of the child after her classes. I was stunned. I expressed my desire to attend the college with the full scholarship, emphasizing that it was my dream. Their response: \"Your dream is no longer important. You need to be responsible. There's another life depending on you now.\" Their words hit me hard. I argued for hours, reminding them that it was my sister's choice, not mine, and that I'd worked tirelessly to achieve my goal. The argument escalated, and in a moment of frustration, I blurted out that they never truly loved me. Their response was equally hurtful, claiming my sister had more potential and that my college dreams were insignificant compared to her needs. I am at a loss. I've always been the responsible child, focusing on my studies and avoiding unnecessary complications. Now, after all my efforts, my dream seems to be slipping away. I don't know what to do next.",
    },
    {
      text: "input: My wife ran away with the cable guy 2 weeks before our wedding",
    },
    {
      text: "output: Unbelievable, right? I thought I had it all. A beautiful fiancée, a dream wedding planned, and a promising career. But fate had something else in store for me. Two weeks before our wedding, my world came crashing down when my fiancée, Jessica, ran away with the cable guy. I mean, seriously, the cable guy! Can you believe it? I had been working overtime to pay for our wedding, and I had no idea that my own home was becoming a hotbed for infidelity. It all started when Jessica complained about the cable connection. She said it was spotty and that she was missing her favorite shows. I called the cable company, and they sent a technician named Chad. Chad was charming, or so I thought. He had a disarming smile and a friendly demeanor. I welcomed him into our home, never suspecting that he would wreak havoc on my life. Over the next few weeks, Chad visited our house several times to fix various cable issues. Each time, Jessica seemed more and more smitten with him. I noticed the way she giggled at his jokes and how she would linger near him, even after he had finished his work. I tried to ignore it, thinking it was just my imagination. But then, one day, I came home early from work and found them in our living room, kissing passionately. I was devastated. I confronted Jessica, and she tearfully confessed that she had fallen in love with Chad. She said that he made her feel alive and that she couldn't resist his charm. I was heartbroken. I couldn't believe that the woman I had planned to spend the rest of my life with would betray me in such a cruel way. I called off the wedding, and Jessica packed her bags and left with Chad. I was left alone, shattered and humiliated. The worst part was that all our friends and family knew about the upcoming wedding. I had to face their pity and disappointment. It was a dark time in my life. I felt like a failure. I had lost the love of my life, my dream wedding, and the respect of those around me. But I knew I had to pick myself up and move on. I threw myself into my work and started spending more time with my friends and family. Slowly but surely, I began to heal. A few months later, I met someone else. She was kind, compassionate, and supportive. We started dating, and eventually, we got married. I'm now happily married with two beautiful children. I still think about Jessica sometimes, but I know that I'm better off without her. She made her choice, and I've made mine. I've found happiness and fulfillment in my new life, and I'm grateful for every day.",
    },
    {
      text: "input: I was fired from my job, became homeless, and now I'm a millionaire",
    },
    {
      text: "output: It all started with a pink slip. I was a dedicated employee at a tech company, working long hours and giving it my all. But one day, the CEO walked in and announced layoffs. I was among the unlucky ones who were let go. Jobless and devastated, I tried to stay positive and applied for countless jobs, but the rejections kept piling up. My savings dwindled, and soon I was facing eviction. I had to make a tough decision: give up my apartment and become homeless. I sold most of my belongings, packed the rest into my car, and started couch surfing at friends' places. It was a humiliating experience, but I was determined to get back on my feet. One day, while I was at a coffee shop, I overheard two guys talking about a new app they were developing. I approached them and offered my help. They were impressed with my skills and agreed to let me join their team. We worked tirelessly, day and night, fueled by our shared passion for technology. The app became a huge success, and we were able to sell it for a substantial amount of money. I had finally struck gold. With my newfound wealth, I bought a house, invested in stocks, and started a foundation to help people who were struggling financially. I also reconnected with my family and friends, who had been incredibly supportive during my difficult times. I learned that life can change in an instant, but with determination and perseverance, it's possible to turn even the most challenging situations into opportunities for growth and success.",
    },
    {
      text: "input: My wife and I use this one trick to travel the WORLD for FREE",
    },
    {
      text: "output: You won't believe this, but my wife and I have been traveling the world for free for the past five years. It all started when we stumbled upon a little-known secret: house sitting. That's right, we take care of people's homes while they're away, and in return, we get to live in their houses for free. It's like a dream come true! We've house sat in over 20 countries so far, from Thailand to Italy to Argentina. We've stayed in mansions, villas, and even a castle. We've met amazing people, tried delicious food, and seen incredible sights. And the best part is, we haven't paid a dime for accommodation. Here's how we do it: We use a website called TrustedHousesitters. It's a platform that connects homeowners with responsible and trustworthy house sitters. We create a profile, list our skills and experience, and then start browsing listings. When we find a house sit that interests us, we send a message to the homeowner and arrange a video call to get to know each other. If they like us, they'll book us for the house sit. It's that simple! We've house sat for all sorts of people, from busy professionals to retirees to families with young children. We've taken care of pets, plants, and even a pet pig named Kevin. We've also had some amazing experiences, like attending a traditional Thai cooking class, going on a safari in South Africa, and learning how to make pasta from an Italian grandmother. House sitting has changed our lives. It's given us the freedom to travel the world, meet new people, and learn about different cultures. We've made lifelong friends and created memories that we'll cherish forever. If you're looking for a way to travel the world for free, I highly recommend house sitting. It's an incredible experience that will open your eyes to the world.",
    },
    {
      text: "input: I went undercover as a maid to find out if my husband was cheating on me",
    },
    {
      text: 'output: My husband, Mark, had been acting strange lately. He was working late, coming home smelling of perfume, and avoiding eye contact. My gut told me something was wrong, but I couldn\'t bring myself to confront him. So, I hatched a plan. I would go undercover as a maid and infiltrate his office. I bought a cheap maid\'s uniform, complete with a mop and bucket, and set out to catch Mark in the act. I arrived at his office building early and slipped into the uniform. I then proceeded to clean the hallways, all the while keeping an eye out for Mark. After an hour of cleaning, I finally spotted him. He was in his office, with his door closed. I took a deep breath and knocked. "Housekeeping," I announced. Mark opened the door, and his eyes widened in surprise. "Uh, I don\'t need any cleaning today," he said. "I\'m just about to leave." I smiled and said, "No problem, sir. I\'ll just finish up in here." I stepped into his office and began to tidy up his desk. As I did, I couldn\'t help but notice a framed photo of a woman on his desk. She was beautiful, with long dark hair and piercing blue eyes. I felt a pang of jealousy. Could this be the woman he was cheating on me with? I decided to take a closer look at the photo. As I leaned in, I gasped. It was me! I was the woman in the photo. Mark had framed a photo of me and put it on his desk. I was so relieved and embarrassed. I quickly finished cleaning up and left the office. I confronted Mark later that night and told him about my little adventure. He laughed and said he had been planning to surprise me with a framed photo of us for our anniversary. He had no idea I would go to such lengths to catch him "cheating." We both had a good laugh, and our relationship is stronger than ever. I guess you could say I cleaned up pretty well that day!',
    },
    {
      text: `input: ${title}`,
    },
    {
      text: "output: ",
    },
  ];

  const result = await model.generateContent({
    contents: [{ role: "user", parts }],
    generationConfig,
    safetySettings: SAFETY_SETTINGS,
  });

  const { response } = result;
  return response.text();
}
